### ISSUE TITLE
When Tomcat server is stoped getting following exception using java8 and tomcat 8

### ISSUE THREAD

**Issue by venkateshkyama** [allcolor/YaHP-Converter#42]
isconnected from the target VM, address: '127.0.0.1:56625', transport: 'socket'
25-Mar-2016 12:30:55.049 INFO [main] org.apache.catalina.core.StandardServer.await A valid shutdown command was received via the shutdown port. Stopping the Server instance.
25-Mar-2016 12:30:55.050 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8086"]
25-Mar-2016 12:30:55.105 INFO [main] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["ajp-nio-50903"]
25-Mar-2016 12:30:55.160 INFO [main] org.apache.catalina.core.StandardService.stopInternal Stopping service Catalina
25-Mar-2016 12:30:55.187 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8086"]
25-Mar-2016 12:30:55.190 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["ajp-nio-50903"]
25-Mar-2016 12:30:55.191 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8086"]
25-Mar-2016 12:30:55.191 INFO [main] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["ajp-nio-50903"]
Destroying YAHP ClassLoader Tree
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
java.lang.NoClassDefFoundError
    at org.allcolor.yahp.converter.CClassLoader.class$(CClassLoader.java:90)
    at org.allcolor.yahp.converter.CClassLoader.destroy(CClassLoader.java:579)
    at org.allcolor.yahp.converter.CYaHPConverter.destroy(CYaHPConverter.java:101)
    at org.allcolor.yahp.converter.CYaHPConverter.finalize(CYaHPConverter.java:280)
    at org.allcolor.yahp.converter.CYaHPConverter$1.run(CYaHPConverter.java:312)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1318)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1181)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    ... 5 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [java.security.AccessControlContext]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1328)
    at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
    ... 9 more
Destroying YAHP ClassLoader Tree : done
Finalizing classloader : rootLoader/main
Finalizing classloader : rootLoader
Disconnected from server

**Comment by allcolor** [comment]
In tomcat, you must not use the yahp classloader. Put all the relevant jar
under webinf lib and instantiate an instance passing false to the boolean
constructor.

Regards
